linters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - nolintlint
    - lll
    - staticcheck
    - testifylint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  lll:
    line-length: 92 # Set your desired max line length here
    tab-width: 4 # Optional: set the width of tab characters
