# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Httpurr < Formula
  desc "HTTP status codes on speed dial"
  homepage "https://github.com/rednafi/httpurr"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.1/httpurr_Darwin_x86_64.tar.gz"
      sha256 "b03f1b13a851e08b8742ab5fcfd500fcd850e605c38695a7e8ae125dfe212575"

      def install
        bin.install "httpurr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.1/httpurr_Darwin_arm64.tar.gz"
      sha256 "82acefd1222f6228636f2cda6518e0316f46624398adc722defb55c68ac3bb30"

      def install
        bin.install "httpurr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.1/httpurr_Linux_arm64.tar.gz"
      sha256 "ad95e8a68b7c48ddbe2a19f7a45d91d954058748ddb47411e3e6efa57dfc8432"

      def install
        bin.install "httpurr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/httpurr/releases/download/v0.1.1/httpurr_Linux_x86_64.tar.gz"
      sha256 "2bee752e7c93e8d0ff7564d6b39cf7780efdb07cfd395cc9c054a5148133c72c"

      def install
        bin.install "httpurr"
      end
    end
  end
end
