# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkPatrol < Formula
  desc "Detect dead URLs in markdown files"
  homepage "https://github.com/rednafi/link-patrol"
  version "0.1-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.1-alpha/link-patrol_Darwin_x86_64.tar.gz"
      sha256 "5a837b62de87d833a982364c71c91aebbb44357a4b4e72638faa677d38183396"

      def install
        bin.install "link-patrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.1-alpha/link-patrol_Darwin_arm64.tar.gz"
      sha256 "7d57e0ead70e10a980aab15c604ff07d29f7398f14630de6b241954eb389ad13"

      def install
        bin.install "link-patrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.1-alpha/link-patrol_Linux_x86_64.tar.gz"
      sha256 "293454efa12c9032a5cf62b91a05b94c12011662c19924aab65ced492fcd1e50"

      def install
        bin.install "link-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.1-alpha/link-patrol_Linux_arm64.tar.gz"
      sha256 "605a22c9f22b450460742569f7d26ce84bec6c1507edd87dc663e0674711e779"

      def install
        bin.install "link-patrol"
      end
    end
  end
end
