# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkPatrol < Formula
  desc "Detect dead URLs in markdown files"
  homepage "https://github.com/rednafi/link-patrol"
  version "0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.5/link-patrol_Darwin_arm64.tar.gz"
      sha256 "66931c4ab2b4f42c7a9a24f2bfe2d0396851f7f61550279e0fd9ff2265167e59"

      def install
        bin.install "link-patrol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.5/link-patrol_Darwin_x86_64.tar.gz"
      sha256 "995df0117f1dbd3607fb82e721b643acab430edee36987e380fc176179fc4c1b"

      def install
        bin.install "link-patrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.5/link-patrol_Linux_x86_64.tar.gz"
      sha256 "e18ea596b49550bb5ec905c94d0c2a8d83cd6481d5ddf297d8b6fd74b9895789"

      def install
        bin.install "link-patrol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/link-patrol/releases/download/v0.5/link-patrol_Linux_arm64.tar.gz"
      sha256 "8c0168db3fba72bfc6fa25365d1d62cc9a6f9f730a8eecdbeda7054fec6b3e67"

      def install
        bin.install "link-patrol"
      end
    end
  end
end
